ER-allimi/ER-allimi

- er-allimi/src/services/getErList.js
- er-allimi/src/services/index.js
- 응급의료기관 목록정보 조회 요청 함수(getErList) 생성
> [Feat] 응급의료기관 목록정보 조회 요청 함수(getErList) 생성

- er-allimi/src/services/getSrIllAccept.js
- er-allimi/src/services/index.js
- 중증질환자 수용가능정보 조회(getSrIllAccept) 함수 생성
> [Feat] 중증질환자 수용가능정보 조회

- er-allimi/src/services/getErList.js
- getErList 함수에서 console 삭제
- getErList 함수에서 item을 반환하는 return문 추가
> [Feat] getErList 함수 return문 추가

- er-allimi/src/main.jsx
- QueryClient에 defaultOptions 추가
- refetchOnWindowFocus: false
- refetchOnMount: false
> [Feat] QueryClient에 defaultOptions 추가

- er-allimi/src/services/getErMsg.js
- er-allimi/src/services/getErRTavailableBed.js
> [Fix] named export로 바꿈

- er-allimi/src/App.jsx
- er-allimi/src/constants/index.js
- er-allimi/src/constants/pathes.js
- er-allimi/src/main.jsx
- er-allimi/src/pages/Chart.jsx
- er-allimi/src/pages/ChartView.jsx
- er-allimi/src/pages/ErsBoxes.jsx
- er-allimi/src/pages/HpDetailBoxes.jsx
- er-allimi/src/pages/HpDetailPage.jsx
- er-allimi/src/pages/Map.jsx
- er-allimi/src/pages/MapView.jsx
- er-allimi/src/pages/index.js
- er-allimi/src/routers.jsx
- er-allimi/src/utils/index.js
- er-allimi/src/utils/pathes.js
> [Feat] Router 구현

- er-allimi/index.html
- er-allimi/package.json
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/map/CurrentLocationButton.jsx
- er-allimi/src/pages/KakaoMap.jsx
- er-allimi/yarn.lock
- 카카오 맵 삽입
- 줌 컨트롤 박스
- 현재 위치 버튼 클릭 시 현재 위치로 다시 돌아 감.
- 반경 2km 표시
> Feat/카카오 맵 삽입 및 줌컨트롤박스, 현재 위치로 이동 버튼 추

- er-allimi/src/routers.jsx
> [Comment] routers.js 주석 삭제

- er-allimi/.prettierrc
> [Chore] prettier 파일 추가

- er-allimi/src/App.jsx
- er-allimi/src/styles/global.js
- er-allimi/src/styles/index.js
- er-allimi/src/styles/theme.js
- er-allimi/vite.config.js
- src/styles 폴더 생성
- global.js 파일 생성
- theme.js 파일 생성
- App 컴포넌트에 global style과 theme provider 설정
> [Feat] global style, theme 추가

- er-allimi/src/components/index.js
- src/components/index.js 파일 내 icons 경로 수정
> [Refactor] index.js icons 경로 수정

- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Box.jsx
- er-allimi/src/components/ui/index.js
> [Feat] Box 컴포넌트 구현

- er-allimi/src/styles/global.js
- global style에서 p, h1~h6의 default color를 grayDarker로 설정함
> [Feat] globalStyle에서 text color를 grayDarker로 기본 설정

- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Input.jsx
- er-allimi/src/components/ui/index.js
> [Feat] Input 컴포넌트 구현

- er-allimi/src/components/ersBoxes/CurrentLocationInput.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- 현재 위치 박스 내 현재 위치 입력창(CurrentLocationInput) 구현
> [Feat] CurrentLocationInput 구현

- er-allimi/src/components/ersBoxes/CurrentLocationBox.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Box.jsx
- er-allimi/src/components/ui/Button.jsx
- er-allimi/src/components/ui/index.js
- er-allimi/src/pages/ErsBoxes.jsx
- Button 컴포넌트 
- CurrentLocationBox 컴포넌트 
- Button 컴포넌트 구현
- Box 컴포넌트에 className prop 추가 및 style 변경
- CurrentLocationBox 컴포넌트 구현
- ErsBoxes 페이지에 layout 관련 스타일 추가
- 사용자 현 위치 가져오는 것은 추후 추가할 예정
- '위치 찾기' 버튼을 클릭했을 때 주소창이 뜨고 주소 입력을 통해 현 위치를 찾는 것은 추후 추가할 예정
> [Feat] Button 구현 & Box 수정 & CurrentLocationBox 구현 & ErsBoxes에 layout 스타일 추가

- er-allimi/src/components/map/ZoomOutButton.jsx
- er-allimi/src/pages/Map.jsx
- er-allimi/src/styles/global.js
- 줌 아웃 버튼 클릭시 13레벨까지만 올라가게 한계 설정함.
-  지도를 욺기지면 지도 중심 위치로 반경이 이동이 되고 해당 반경 안에 있는 응급실 마커만 표시됨.
- 현재 응급실 리스트는 상태값으로 관리되고 있으나 추후에 리코일로 전역 변수로 관리할 예정임.
- 첫 렌더링 시 디폴트값인 제주도로 이동되고 있으나 추후 root로 진입 시 사용자의 위치를 받아 전역변수로 관리 할 예정
> [Feat] 중심 위치 변경 시 반경 이동 및  응급실 마커 추가

- er-allimi/src/components/app/Navbar.jsx
- er-allimi/src/components/ui/Input.jsx
- er-allimi/src/pages/MapView.jsx
- Navbar/Input/MapView styled 위치 변경
> [Style] Navbar/Input/MapView styled 위치 변경

- er-allimi/src/stories/Input.stories.js
> [Feat] Input stories 구현

- er-allimi/src/pages/MapView.jsx
- MapView 내 스타일 다시 function 안으로 옮김
> [Style] MapView 내 스타일 원위치

- er-allimi/src/components/ersBoxes/ErItem.jsx
- er-allimi/src/components/ersBoxes/ErsBox.jsx
- er-allimi/src/components/ersBoxes/ErsList.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/pages/ErsBoxes.jsx
- ErsList 컴포넌트 구현
- ErItem 컴포넌트 구현
- ErsBox 컴포넌트 구현
- ErsBoxes 페이지에 ErsBox 추가
- ErItem 컴포넌트에서 전화번호 클릭 시, 화면 상단에 '복사되었습니다' 메시지가 뜨게 할 예정
- ErsBox 하단에 pagination을 추가할 예정
> [Feat] ErsList/ErItem/ErsBox 컴포넌트 구현 & [Feat] ErsBoxes 페이지에 ErsBox 추가

- er-allimi/src/components/ersBoxes/ErsBox.jsx
- er-allimi/src/components/ersBoxes/RadiusDropdown.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Dropdown.jsx
- er-allimi/src/components/ui/index.js
- Dropdown 컴포넌트 구현
- RadiusDropdown(반경 드롭다운) 컴포넌트 구현
- ErsBox에 RadiusDropdown 추가 및 스타일 이동
> [Feat] Dropdown/RadiusDropdown 컴포넌트 구현 & [Feat] ErsBox에 RadiusDropdown 추가 및 스타일 이동

- er-allimi/src/components/ersBoxes/ErItem.jsx
- er-allimi/src/components/ersBoxes/ErsBox.jsx
- ErItem 컴포넌트에서 주소나 전화번호 클릭 시 alert 창이 나타나게 처리
- ErsBox 컴포넌트에서 스타일 수정 및 '내 위치 주변 응급실' 타이틀에 응급실 개수 추가
> [Feat] ErItem 주소/전화번호 클릭 시 alert 처리 & [Design] ErsBox 스타일 및 글자 수정

- er-allimi/src/components/ersBoxes/ErsBox.jsx
- er-allimi/src/components/ersBoxes/ErsPagination.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Pagination.jsx
- er-allimi/src/components/ui/index.js
- Pagination 컴포넌트 구현
- ErsPagination 컴포넌트 구현
- ErsBox에 ErsPagination 추가
> [Feat] Pagination/ErsPagination 컴포넌트 구현 & [Feat] ErsBox에 ErsPagination 추가

- er-allimi/src/components/ui/Box.jsx
> [Design] Box 컴포넌트 스타일 수정

- er-allimi/src/services/getErMsg.js
- er-allimi/src/services/getErRTavailableBed.js
> [Fix] API 반환값 body 누락

- er-allimi/src/components/ersBoxes/ErItem.jsx
- ErItem 컴포넌트에서 nth-child를 nth-of-type으로 변경
> [Fix] nth-child 에러 해결

- er-allimi/src/components/ersBoxes/RadiusDropdown.jsx
- er-allimi/src/components/ui/Dropdown.jsx
- er-allimi/src/components/ui/Pagination.jsx
- Pagination
- Pagination 컴포넌트에서 페이지 배경색을 'redLight'에서 'gray'로 변경
- Dropdown 컴포넌트에 className prop 추가
- Dropdown 컴포넌트에서 페이지 숫자 스타일 변경
- RadiusDropdown 컴포넌트에서 Dropdown 너비 고정시킴
> [Design] Pagination 스타일 수정 & [Feat] Dropdown에 className prop 추가 및 스타일 변경 & [Feat] RadiusDropdown 스타일 추가

- er-allimi/src/App.jsx
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/MovingBox.jsx
- er-allimi/src/components/ui/index.js
- movingbox가 올라온 상태
- movingbox가 내려간 상태
- App 페이지에 'overflow: hidden' 스타일 추가
- MovingBox 컴포넌트 구현
> [Design] App 페이지에 overflow: hidden 스타일 추가 & [Feat] MovingBox 컴포넌트 구현

- er-allimi/src/pages/Map.jsx
- er-allimi/src/utils/getErRTavailableBedByColor.js
- er-allimi/src/utils/index.js
- er-allimi/yarn.lock
- 가용병상률에 따라 응급실 마커 색상 변경
- 가용병상률 데이터가 없는 병원들은 default 값으로 gray색상을 줌
- 가용병상률 데이터를 react-query 캐싱 처리할 것
> [Feat]/가용병상률에 따른 응급실 마커 색상 변경

- er-allimi/src/components/map/CurrentLocationOverlay.jsx
- er-allimi/src/components/map/ErMarkerOverlay.jsx
- er-allimi/src/components/map/index.js
- er-allimi/src/pages/Map.jsx
- er-allimi/src/styles/mapOverlay/currentLocationOverlay.module.css
- er-allimi/src/styles/mapOverlay/erMarkerOverlay.module.css
- overlay 컴포넌트를 생성 후 컴포넌트를 HTML 문자열을 반환하였음.
- renderToString 사용시 emotion.styled가 작동되지 않아 module.css를 사용하여 작성하였음
> [Refactor] map overlay 분리

- er-allimi/src/components/ersBoxes/ViewButton.jsx
- ViewButton 컴포넌트 내 아이콘이 정가운데에 위치하도록 스타일 수정
> [Design] ViewButton 스타일 수정

- er-allimi/src/pages/ErsBoxes.jsx
- er-allimi/src/routers.jsx
- ChartView 페이지의 우선순위를 뒤로 미뤘기 때문에, 임시로 아래와 같은 처리를 해주었음
- router에서 chartView path를 주석 처리
- ErsBoxes에서 viewToggle, viewButton를 제거해, 화면에서 ChartView 페이지로 넘어가는 경로를 차단해 주었음
> [Comment] router에서 chartView path 주석처리 & [Feat] ErsBoxes에서 viewToggle, viewButton 제거

- er-allimi/src/App.jsx
- er-allimi/src/hooks/index.js
- er-allimi/src/hooks/useGetUserLocation.js
- er-allimi/src/main.jsx
- er-allimi/src/stores/atoms/index.js
- er-allimi/src/stores/atoms/userLocationState.js
- er-allimi/src/stores/index.js
- main.js에서 Recoil 연결
- stores/atoms 폴더를 만든 후, 사용자의 위치 정보(위도, 경도)를 저장하는 userLocationState atom 생성
- 사용자의 위치 정보를 가져와 userLocationState에 저장하는 useGetUserLocation hook 생성
- App 페이지에 useGetUserLocation hook 추가
> [Feat] React에 Recoil 연결 & [Feat] userLocationState atom 생성 & [Feat] useGetUserLocation hook 생성 및 App에 추가

- er-allimi/src/App.jsx
- er-allimi/src/hooks/index.js
- er-allimi/src/hooks/useFetchErList.js
- er-allimi/src/hooks/useGetUserLocation.js
- useGetUserLocation hook에서 `navigator.geolocation.getCurrentPosition(handleGetCurPosSuccess, handleGetCurPosFail)` 코드를 App 내 useEffect callback function으로 이동시킴
- useGetUserLocation hook이 handleGetCurPosSuccess와 handleGetCurPosFail 함수를 반환하도록 수정
- 응급실 전체 목록 정보를 API 호출하는 useFetchErList hook 생성
- App에서 useFetchErList hook을 활용
> [Feat] useGetUserLocation hook 수정 & [Feat] useFetchErList hook 생성 및 App에서 활용

- er-allimi/src/components/index.js
- er-allimi/src/pages/Map.jsx
- er-allimi/src/stores/atoms/userLocationState.js
- 현재 위치 recoil에서 받아와  mapView와 연결
- 현재 위치를 받아올 수 없을땐, 초기값으로 서울역으로 뜸. 
- 첫 렌더링 시 초기값인 서울역으로 지도가 그려진 후 현재 위치로 이동
> [Feat] 현재 위치 recoil에서 받아와 mapview 연결

- er-allimi/src/App.jsx
- er-allimi/src/constants/pathes.js
- er-allimi/src/hooks/index.js
- er-allimi/src/hooks/useFetchErsRTavailableBed.js
- er-allimi/src/services/getErRTavailableBed.js
- er-allimi/src/stores/index.js
- er-allimi/src/stores/selectors/ersWithRadiusState.js
- er-allimi/src/stores/selectors/index.js
- er-allimi/src/stores/selectors/sortedErsWithRadiusState.js
- er-allimi/src/utils/pathes.js
- getErRTavailableBed axios에 numOfRows 옵션 추가
- 전체 응급실 실시간 가용 병상 정보를 가져오는 useFetchErsRTavailableBed hook 생성 및 App에서 활용
- ersWithRadiusState atom에서 hpId를 소문자 hpid로 수정
- sortedErsWithRadiusState atom 수정 및 index 파일에 추가
- hospital detail path에 stage1과 stage2는 빼고 hpId만 들어가게 수정
> [Feat] getErRTavailableBed axios에 numOfRows 옵션 추가 & [Feat] useFetchErsRTavailableBed hook 생성 및 App에 연결 

- er-allimi/src/components/ersBoxes/ErsContent.jsx
- [Feat] '내위치 주변 응급실' 제목에 응급실 개수 수정(데이터 연결)
> [Feat] '내위치 주변 응급실' 제목에 응급실 개수 수정

- er-allimi/src/components/app/Navbar.jsx
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
> [Feat] 뒤로 가기 버튼 구현

- er-allimi/src/pages/Map.jsx
- (기존) 반경 변경 시 중심위치 이동해야만 circle 오버레이, 응급실 마커 변경
- (현재) 반경 변경 시 즉시 circle 오버레이, 응급실 마커 반영됨
-
> [Fix] 반경 변경 시 즉시 circle 오버레이 변경

- er-allimi/src/pages/Map.jsx
- er-allimi/src/utils/index.js
- er-allimi/src/utils/pathes.js
- 응급실 마커 클릭 시 해당 병원 디테일 페이지로 이동
- 현재 경로값을 입력하면 디테일 페이지인지 확인하고 파라미터값을 가져옴
-  
- 병원 디테일 페이지로 이동 시 맵이 현재 좌표 위치로 이동함.
- 클릭한 병원으로 지도 중심 위치 바꿀 필요가 있음
> [Feat] 응급실 마커 클릭 시 해당 병원 디테일 페이지로 이동

- er-allimi/src/components/ersBoxes/EmptyBox.jsx
- er-allimi/src/components/ersBoxes/ErsList.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- 지도 중심 위치에 응급실이 없을 때, '내 위치 주변 응급실' 박스에서 응급실이 없다는 문구 나타남
> [Feat] 응급실이 없을 때 문구 나타남

- er-allimi/src/components/hpDetailBoxes/HpMessageBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpMessageItem.jsx
- 메시지 item 컴포넌트 + dummy data
- 메시지 박스 컴포넌트에서 react-query 훅 호출
> [Feat] message react query

- er-allimi/src/components/hpDetailBoxes/HpSrIIIBox.jsx
- er-allimi/src/hooks/index.js
- er-allimi/src/hooks/useFetchHpSrIII.js
- 중증질환정보react query 커스텀 훅 생성
- 중증질환정보 박스에서 react query 커스텀 훅 호출
-
> [Feat] 중증질환정보 react query 커스텀 

- er-allimi/src/utils/index.js
- getIpFromPathHospitalDetail 경로 삭제
> [fix] 경로 삭제

- er-allimi/src/pages/HpDetailPage.jsx
- er-allimi/src/stores/index.js
- er-allimi/src/stores/selectors/hpDetailState.js
- er-allimi/src/stores/selectors/index.js
- ersListState, ersRTavailableBedState에서 targetHpId와 일치한 데이터 필터링
- 중증환자 API 조회를 위해 stage1, stage2 반환함
> [Feat] hpDatilState selector 생성

- er-allimi/src/hooks/index.js
- er-allimi/src/hooks/useMarker.jsx
- er-allimi/src/pages/Map.jsx
- sortedRTavailableBed state에 따라 마커가 변함(거리순, 가용병상 순으로 숫자와 색깔이 변함)
> [Refactor] useMarker로 마커 생성부분 Map에서 분리

- er-allimi/src/pages/Map.jsx
> [Feat] 클릭한 병원 중앙으로 이동

- er-allimi/src/pages/Map.jsx
- 중심좌표 이동 시 
> - 마커 재생성
> - 클린업 함수로 기존 마커와 기존 반경 오버레이 삭제 (반경 오버레이 상태관리 삭제)
> [Refactor] 불필요한 state 관리 제거

- er-allimi/src/components/hpDetailBoxes/AdultModel.jsx
- er-allimi/src/components/hpDetailBoxes/HpSrIllContent.jsx
- er-allimi/src/components/ui/Tooltip.jsx
- content 타입이 array인지 확인할 때, `typeof content === 'object'`가 아닌 `Array.isArray(content)`로 수정
- AdultModel에서 해당 부위에 대한 데이터가 있을 때만 노란색으로 표시되도록 수정
- hpDetailState selector을 사용해 HpSrIll에 실제 데이터 연결
> [Refactor] Tooltip 수정 & [Fix] AdultModel 수정 & [Feat] HpSrRill에 실 데이터 연결

- er-allimi/src/components/hpDetailBoxes/HpInfoContent.jsx
- HpInfo에서 주소 행과 전화번호 행 사이를  줄임
> [Design] HpInfo에서 행간  줄임

- er-allimi/src/pages/HpDetailBoxes.jsx
- 가용 병상 정보 => 실시간 응급실 가용병상 박스, 실시간 입원실 가용 병상 정보 생성
- 중증질환자 정보 => 중증 질환 정보 박스
-
> [Feat] 정보 없는 박스들 분기점 생성

- er-allimi/src/components/ersBoxes/ErsBox.jsx
- er-allimi/src/components/ersBoxes/ErsList.jsx
- er-allimi/yarn.lock
- ERsBox 자체 height -> min-height로 수정
- ErsList 내 EmptyBox height 수정
> [Refactor] ERsBox height 수정

- er-allimi/src/components/ersBoxes/ErItem.jsx
- er-allimi/src/components/hpDetailBoxes/HpInfoContent.jsx
- HpInfo 각 이름/주소/번호에 title 속성 추가
- ErItem 각 이름/주소/번호에 title 속성 추가
> [Refactor] HpInfo 각 이름/주소/번호에 title 속성 추가

- er-allimi/src/components/hpDetailBoxes/HpMessageItem.jsx
- er-allimi/src/components/hpDetailBoxes/HpMessageList.jsx
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/AutoPlaySlider.jsx
- er-allimi/src/components/ui/Slider.jsx
- er-allimi/src/components/ui/index.js
- Slider/AutoPlaySlider 구현
- HpMessageItem에서 padding 늘림
- HpMessageList에 AutoPlaySlider 활용
> [Feat] Slider/AutoPlaySlider 구현 & [Feat] HpMessageList에 AutoPlaySlider 활용

- er-allimi/src/components/hpDetailBoxes/HpMessageBox.jsx
- er-allimi/src/components/ui/AutoPlaySlider.jsx
- er-allimi/src/components/ui/Slider.jsx
- Slider 컴포넌트에 sliding, infinite 기능 추가
- AutoPlaySlider 컴포넌트에 sliding, infinite 기능 추가
- HpMessageBox width 스타일 수정
> [Feat] Slider/AutoPlaySlider에 sliding, infinite 기능 추가

- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedContent.jsx
- er-allimi/src/components/ui/ScrollBar.jsx
- max-height값을 주어 전체 레이아웃에서 벗어나지 않게 함
> [Feat] 반응형 고려하여 박스 크기 조절

- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- 가이드 내용이 크기를 많이 차지하여 information 아이콘 호버시 해당 내용이 나오게 수정함.
-
> [Feat] 가이드 내용 tooltip으로 변경

- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedContent.jsx
> [Fix] 지도 축척 보이게 사이즈 줄임

- er-allimi/src/pages/Map.jsx
- 위치 찾기로 위치 설정 시 해당 위치로 중심위치 즉시 이동
> [Fix] 위치 찾기로 위치 설정 시 중심 위치 이동 수정

- er-allimi/src/components/hpDetailBoxes/HpInfoContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedContent.jsx
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Skeleton.jsx
- er-allimi/src/components/ui/index.js
- er-allimi/src/pages/HpDetailBoxes.jsx
- skeleton UI 구현
- 병원 기본 정보 박스, 실시간 응급실 가용 병상 정보 박스, 실시간 입원실 가용 병상 정보 박스 적용
-
> [Feat] skeleton UI 구현 및 HpDetail 박스들 적용

- er-allimi/src/components/hpDetailBoxes/HpInfoContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpSrIllContent.jsx
- er-allimi/src/components/hpDetailBoxes/SelectButtons.jsx
- er-allimi/src/components/hpDetailBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Button.jsx
- er-allimi/src/components/ui/MovingBox.jsx
- er-allimi/src/pages/HpDetailBoxes.jsx
- er-allimi/src/stores/atoms/index.js
- er-allimi/src/stores/atoms/selectedHpDetailContentState.js
- er-allimi/src/stores/index.js
- Button propType 변경
- HpInfoContent 스타일링 변경
- HpSrIllContent 스타일링 변경
- MovingBox 애니메이션 제거
- selectedHpDetailContentState atom 생성
- HpDetailBoxes 스타일 수정
- SelectButtons 구현
- HpMovingBox에 SelectButtons 추가
> [Feat] HpDeatil 페이지 moving box 내 content 넣음

- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedContent.jsx
- 반응형에 따라 실시간 응급실/입원실 가용병상 타이틀의 폰트 크기 수정
> [Design] 반응형에 따라 실시간 응급실/입원실 가용병상 타이틀의 폰트 크기 수정

- er-allimi/src/components/ersBoxes/CurrentLocationInput.jsx
- CurrentLocationInput rightIcon 타입 에러 수정
> [Fix] CurrentLocationInput rightIcon 타입에러 수정

- er-allimi/src/pages/Map.jsx
> [Fix] 맵 컨트롤 박스 레이아웃 반응형에 따른 위치 변경

- er-allimi/src/App.jsx
- er-allimi/src/components/app/Navbar.jsx
- er-allimi/src/components/ersBoxes/ErsMovingBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- Navber (sm < 화면 너비 < md일 때)
- Navber (화면 너비 < sm일 때)
- Navbar 뷰포트 md이하일 때 height 감소
- App, ErsMovingBox, HpMovingBox height도 수정
> [Design] Navbar 뷰포트 md이하일 때 height 감소

- er-allimi/src/components/hpDetailBoxes/ErChart.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- 기존 flex => grid로 변경
-  sm, md 일때 차트 width 120px로 변경
- 반응형에 따른 차트 레이아웃 변경
> [Feat] 실시간 응급실 가용 병상 content 반응형

- er-allimi/index.html
- er-allimi/src/components/hpDetailBoxes/AdultModel.jsx
- er-allimi/src/components/hpDetailBoxes/EtcSrIll.jsx
- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpSrIllContent.jsx
- er-allimi/src/components/hpDetailBoxes/KidModel.jsx
- er-allimi/src/components/hpDetailBoxes/Models.jsx
- er-allimi/src/components/hpDetailBoxes/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Popover.jsx
- er-allimi/src/components/ui/index.js
- er-allimi/src/constants/bodyParts.js
- er-allimi/src/constants/index.js
- Popover 컴포넌트 구현
- HpMovingBox에 `className='hpMovingBox'` 추가
- HpSrIllContent에서 모델들 분리해 따로 Models 생성
- bodyPart constants 생성
- 뷰포트 md 이하일 때, AdultModel, KidModel, EtcSrIll에서 Tooltip 대신 Popover 띄우게 수정
> [Feat] Popover 구현 &  [Feat] 뷰포트 md 이하일 때, Tooltip 대신 Popover 띄우게 수정

- er-allimi/src/components/ersBoxes/ErsList.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedContent.jsx
- er-allimi/src/components/ui/Skeleton.jsx
- 실시간 응급실 가용병상 박스, 실시간 입원실 가용병상 박스 스켈레톤 UI -> 스피너 UI로 변경
- 메인 페이지 스켈레톤 UI 추가
> 가용 병상 content 스켈레톤 추가
> Feat/loading UI

- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- er-allimi/src/components/hpDetailBoxes/SelectButtons.jsx
> [Design] SelectButtons 아래 마진 증가

- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedContent.jsx
- er-allimi/src/components/ui/Table.jsx
- md 이하일때 표의 스크롤 없애고 너비 100%로 박스 전체를 채움.
- md 이하일때 전체적인 content에 padding-bottom 적용
- lg 일때 위치 찾기 박스가 사라짐으로 인해 높이 조정 수정함.
> [Feat] 반응형 표 사이즈 조정 및 실시간 입원실 가용 병상 박스 높이 조정

- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- lg일땐 information은 Tooltip으로 구현
- md 이하일땐 information Popover로 변경
-
> [Feat] md 이하일땐 Tooltip -> Popover로 변경

- er-allimi/index.html
> [Feat] index.html head에 구글 태그 추가

- er-allimi/src/styles/global.js
> [Rename] NotoSans 폰트 파일을 public으로 옮김

- er-allimi/src/pages/ErsBoxes.jsx
- 에러 사진
- 해결 후 사진
- 박스에 overflow hidden 처리
> [Fix] md 이하일때, 내용 너비에 따라 상단 박스가 커짐

- er-allimi/src/pages/Map.jsx
- er-allimi/src/pages/NotFoundPage.jsx
- er-allimi/src/pages/index.js
- er-allimi/src/routers.jsx
- 잘못된 경로 진입 시 NotFoundPage로 이동
> [Feat] 잘못된 경로 진입 시 NotFoundPage 이동

- er-allimi/package.json
- er-allimi/src/components/ersBoxes/ErItem.jsx
- er-allimi/src/components/hpDetailBoxes/HpInfoContent.jsx
- er-allimi/yarn.lock
- react-copy-to-clipboard 사용해 복사
> [Refactor] react-copy-to-clipboard 사용해 복사

- er-allimi/src/components/ersBoxes/ErItem.jsx
> [Feat] 현재 위치와 떨어진 거리 추가

- er-allimi/google086db4e17dea05af.html
> [Feat] Search Console html 파일 추가

- er-allimi/src/components/ersBoxes/ErsContent.jsx
- er-allimi/src/components/ersBoxes/ErsList.jsx
> [Fix] ErsContent 스크롤 수정(movingBox 안내려가는 이슈 해결)

- er-allimi/index.html
- Google Search Console 태그 html head에 추가
> [Feat] Google Search Console 태그 html head에 추가

- er-allimi/src/components/app/Navbar.jsx
- er-allimi/src/components/ersBoxes/HpSearchInput.jsx
- er-allimi/src/components/ersBoxes/MatchedHpItem.jsx
- er-allimi/src/components/ersBoxes/MatchedHpList.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/pages/ErsBoxes.jsx
- 입력 전
- 입력 후
- HpSearchInput(의료기관 검색창) 구현
- ErsBoxes에 center layout 추가
- Navbar에 HpSearchInput 추가
> [Feat] HpSearchInput(의료기관 검색창) 구현

- er-allimi/src/components/ui/MovingBox.jsx
> [Fix] MovingBox width 수정

- er-allimi/src/components/hpDetailBoxes/HpSrIllContent.jsx
- er-allimi/src/hooks/useFetchHpSrIII.jsx
- select옵션을 사용해서 데이터 fectch 성공 시 가공함.
- 기존에 data의 유효성 검사를 할 필요가 없음
> [Refactor] select 옵션을 사용하여 데이터 가공

- er-allimi/package.json
- er-allimi/src/components/hpDetailBoxes/HpSrIllContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpSrIllData.jsx
- er-allimi/src/components/hpDetailBoxes/index.js
- er-allimi/src/components/index.js
- er-allimi/src/hooks/useFetchHpSrIII.jsx
- er-allimi/yarn.lock
- react-error-boundary 패키지 설치
- useFetchHpSrIll 내 useQuery에 suspense 옵션 추가
- HpSrIllData 컴포넌트 생성 후, HpSrIllContent에 있던 useFetchHpSrIll 호출을 옮겨옴
- HpSrIllContent에서 HpSrIllData 컴포넌트를 Suspense와 ErrorBoundary로 감싸주어 로딩 및 에러 처리
> [Refactor] 중증질환 - Suspense, ErrorBoundary를 이용해 선언적 코드화

- er-allimi/src/components/ui/MovingBox.jsx
- MovingBox 이동 시 transition 추가
> [Refactor] MovingBox 이동 시 transition 추가

- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- HpMovingBox 완전히 올라올 때 message 뜨게 수정
> [Refactor] HpMovingBox 완전히 올라올 때 message 뜨게 수정

- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- er-allimi/src/components/ui/MovingBox.jsx
> [Refactor] moving box transition 제거

- er-allimi/src/services/getSrIllAccept.js
- getSrIllAccept 함수에 numOfRows 옵션 추가
> [Fix] getSrIllAccept 함수에 numOfRows 옵션 추가

- er-allimi/src/pages/Map.jsx
> [Fix] 지도 위 반경 오버레이 터치 드래그 이슈 해결

- er-allimi/index.html
- Naver Search Advisor에 대한 meta 태그 추가
> [Feat] Naver Search Advisor에 대한 meta 태그 추가

- er-allimi/sitemap.xml
- er-allimi root 폴더에 sitemap.xml 생성
> [Feat] sitemap.xml 생성

- er-allimi/src/hooks/useMarker.jsx
- er-allimi/src/pages/Map.jsx
> [Comment] 주석 및 콘솔 삭제

- er-allimi/.gitignore
- er-allimi/src/pages/NotFoundPage.jsx
AWS S3 + cloudfront +  route53 배포
> [Deploy] AWS S3 + cloudfront +  route53 배포

- er-allimi/src/components/ui/Dropdown.tsx
- er-allimi/tsconfig.json
- Dropdown 파일 ts 변환
- tsconfig 파일의 compilerOptions에 `allowJs: true` 옵션 추가
> [Refactor] Dropdown 파일 ts 변환

- er-allimi/src/components/ui/Input.tsx
> [Refactor] Input 파일 ts 변환

- er-allimi/src/components/ui/Popover.tsx
> [Refactor] Popover 파일 ts 변환

- er-allimi/src/components/ui/Popover.tsx
- er-allimi/src/components/ui/Toggle.tsx
- er-allimi/src/components/ui/Tooltip.tsx
- Tooltip, Toggle 파일 ts로 변환
- Tooltip, Toggle에서 propTypes import 코드 제거
- Popover ContentBox에 direction prop 제거
> [Refactor] Tooltip, Toggle 파일 ts로 변환

- er-allimi/src/components/ui/Slider.tsx
> [Refactor] Slider 파일 ts 변환

- er-allimi/src/components/ui/AutoPlaySlider.tsx
> [Refactor] AutoPlaySlider 파일 ts 변환

- er-allimi/src/components/ersBoxes/CurrentLocationBox.tsx
- er-allimi/src/components/ersBoxes/CurrentLocationInput.tsx
- CurrentLocationBox 파일 ts로 변환
- CurrentLocationInput 파일 ts로 변환
> [Refactor] CurrentLocationBox, CurrentLocationInput 파일 ts로 변환

- er-allimi/global.d.ts
- er-allimi/src/components/ersBoxes/ErsBox.tsx
- er-allimi/src/components/ersBoxes/ErsContent.tsx
- er-allimi/src/components/ersBoxes/ErsMovingBox.tsx
- er-allimi/src/components/ersBoxes/PostCodeButton.tsx
- er-allimi/src/services/getCoorByAddress.ts
- getCoorByAddress 함수 내 에러 처리 코드 추가
- Window 인터페이스에 daum 속성의 타입 추가]
- PostCodeButton 파일 ts 변환
- ErsBox 파일 ts 변환
- ErsMovingBox 파일 ts 변환
- ErsContent 파일 ts 변환
> [Refactor] components/ersBoxes 폴더 내 일부 파일들 ts로 변환

- er-allimi/global.d.ts
- er-allimi/src/components/ersBoxes/ErItem.tsx
- er-allimi/src/components/ersBoxes/ErsList.tsx
- global.d.ts에 '반경 내 응급실' 데이터의 타입 정의
- ErsList 파일 ts 변환
- ErItem 파일 ts 변환
> [Refactor] ErsList, ErItem 파일 ts 변환

- er-allimi/src/components/ersBoxes/ErsPagination.tsx
- er-allimi/src/components/ersBoxes/RadiusDropdown.tsx
- er-allimi/src/components/ersBoxes/SortingButtons.tsx
- ErsPagination 파일 ts 변환
- RadiusDropdown 파일 ts 변환
- SortingButtons 파일 ts 변환
> [Refactor] ErsPagination/RadiusDropdown/SortingButtons 파일 ts 변환

- er-allimi/src/components/hpDetailBoxes/HpInfoBox.tsx
- er-allimi/src/components/hpDetailBoxes/HpInfoContent.tsx
- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedContent.jsx
- er-allimi/src/stores/selectors/hpDetailState.js
- hpDetailState에서 조건 미충족 시 empty array가 아닌 null 값을 반환하도록 수정
- HpRtErAvailableBedContent 컴포넌트에서 hpDetail recoil state 값 확인 코드 수정
- HpRtHrAvailableBedContent 컴포넌트에서 hpDetail recoil state 값 확인 코드 수정
- HpInfoContent 컴포넌트에서 hpDetail recoil state 값 확인 코드 수정 및 ts 파일로 변환
- HpInfoBox 파일 ts로 변환
> [Refactor] hpDetailState에서 조건 미충족 시 empty array가 아닌 null 값을 반환하도록 수정

- er-allimi/naver54e5ebb3b6fb160e2c72070b164acbf0.html
- Naver Search Advisor 소유권 확인 html 파일 추가
> [Feat] Naver Search Advisor 소유권 확인 html 파일 추가

- er-allimi/index.html
> [Fix] open graph image 주소 변경

- er-allimi/src/components/hpDetailBoxes/HpMessageBox.tsx
> [Refactor] HpMessageBox 파일 ts로 변환

- er-allimi/src/components/hpDetailBoxes/HpMessageItem.tsx
- er-allimi/src/components/hpDetailBoxes/HpMessageList.tsx
- HpMessageList, HpMessageItem 파일 ts로 변환
- HpMessageList 컴포넌트에서 AutoPlaySlider 내 renderSlice 속성에서 타입 에러가 떴지만 아직 해결하진 못함
> [Refactor] HpMessageList, HpMessageItem 파일 ts로 변환
