ER-allimi/ER-allimi

- er-allimi/src/components/ersBoxes/ErItem.jsx
- ErItem 컴포넌트에서 좌우로 약간 padding을 주고, 주소/전화번호 글자 크기를 줄임
> [Design] ErItem 컴포넌트 스타일 수정

- er-allimi/src/components/app/Navbar.jsx
- Navbar 컴포넌트에서 화면 너비가 sm 이하일 때, 버거 아이콘을 클릭해도 sub-navbar가 나타나지 않아 z-index를 추가해줬음
> [Design] subNavbar에 z-index 추가

- er-allimi/src/components/ersBoxes/ErItem.jsx
- er-allimi/src/components/ersBoxes/ErsBox.jsx
- er-allimi/src/components/ersBoxes/ErsContent.jsx
- er-allimi/src/components/ersBoxes/ErsList.jsx
- er-allimi/src/components/ersBoxes/ErsMovingBox.jsx
- er-allimi/src/components/ersBoxes/RadiusDropdown.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/Dropdown.jsx
- er-allimi/src/components/ui/MovingBox.jsx
- er-allimi/src/components/ui/Pagination.jsx
- er-allimi/src/pages/ErsBoxes.jsx
- (화면 너비 md 이상) ErsBox
- (화면 너비 md 이하) ErsMovingBox
- ErsContent 컴포넌트 생성
- ErsBox에서 내부 content 전부를 ErsContent로 이동시킴
- MovingBox에 children prop 추가 및 스타일 변경
- ErsMovingBox 컴포넌트 구현
- ErsBoxes 페이지에 ErsMovingBox 추가
- ErsList에 className prop 추가
- ErsList 내 스타일을 ErsContent로 이동시킴
- ErItem 스타일 추가 및 수정
- Pagination 스타일 수정
- Dropdown 스타일 수정
- RadiusDropdown에 className prop 추가
> [Refactor] ErsBox에서 내부를 ErsContent 컴포넌트로 빼냄 & [Feat] ErsMovingBox 컴포넌트 구현 & [Feat] ErsBoxes에 ErsMovingBox 추가

- er-allimi/src/components/ersBoxes/CurrentLocationInput.jsx
- er-allimi/src/hooks/useGetUserLocation.js
- er-allimi/src/stores/atoms/userLocationState.js
- er-allimi/src/utils/getAddressByCoor.js
- er-allimi/src/utils/index.js
- 사용자의 좌표(위도, 경도)로부터 주소 정보를 반환하는 getAddressByCoor 함수 구현
-  userLocationState atom에 address 필드 추가
- useGetUserLocation hook에서 좌표로부터 주소 정보 가져와 userLocationState atom에 위도/경도와 함께 주소도 저장
- CurrentLocationInput 컴포넌트에서 userLocationState atom 내 저장된 주소 가져와서 입력창에 표시
> [Feat] getAddressByCoor 함수 구현 & [Feat] userLocationState atom에 address 필드 추가한 후, 좌표로부터 주소 정보 가져와 저장

- er-allimi/src/pages/Map.jsx
- 마커 z-index의 최댓값보다 인포인도우 z-index가 더 크게 수정
> [Fix] 마커 z-index의 최댓값보다 인포인도우 z-index가 더 크게 수정

- er-allimi/src/components/ersBoxes/ErItem.jsx
- er-allimi/src/components/ersBoxes/ErsContent.jsx
- er-allimi/src/components/ersBoxes/ErsList.jsx
- er-allimi/src/components/ersBoxes/ErsPagination.jsx
- er-allimi/src/components/ersBoxes/PostCodeButton.jsx
- er-allimi/src/components/ersBoxes/RadiusDropdown.jsx
- er-allimi/src/components/ersBoxes/SortingButtons.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/index.js
- er-allimi/src/constants/index.js
- er-allimi/src/constants/pagination.js
- er-allimi/src/stores/atoms/ersPaginationState.js
- er-allimi/src/stores/atoms/index.js
- er-allimi/src/stores/index.js
- er-allimi/src/stores/selectors/sortedErsWithRadiusState.js
- MapView 페이지
- 정렬 기준 변경 시
- 반경 변경 시
- 페이지 변경 시
- MapView 페이지에서 '내 위치 주변 응급실' 박스 내 현재 페이지 정보를 담는 ersPaginationState atom 추가
- 페이지당 응급실 개수(ERS_CNT_PER_PAGE) constant 생성
-  sortedErsWithRadiusState selector 수정
- 입원실 일반(hvgc) -> 응급실 일반(hvec)
- availableBedInfo 데이터가 없는 응급실의 경우, '가용 병상 개수 순'으로 정렬 시 가장 뒤에 오도록 구현
- ErsContent 컴포넌트에서 정렬 버튼들을 떼어내 따로 SortingButtons 컴포넌트로 생성
- SortingButtons 컴포넌트에서 정렬 기준 변경 시, sortingState 값 변경
- RadiusDropdown 컴포넌트에서 반경 변경 시, radiusState 값을 변경하고 ersPaginationState 값은 1로 초기화
- ErsPagination 컴포넌트에 페이지 변경 시, ersPaginationState 값 변경
- PostCodeButton 컴포넌트에서 complete 시, mapCenterPointState 값을 해당 좌표로 변경하고 ersPaginationState 값은 1로 초기화
- ErsList 컴포넌트에서 sortedErsWithRadiusState 데이터 연결 및 현재 페이지 별로 데이터를 끊어서 보여줌
- ErItem 컴포넌트에 데이터 연결
- '내 위치 주변 응급실(15)' 제목 안에 있는 응급실 총 개수는 차후 …
> [Feat] ersPaginationState atom 추가 & [Fix] sortedErsWithRadiusState selector 수정 & [Feat] SortingButtons 생성 & [Feat] 각 컴포넌트에 recoil state 연결

- er-allimi/src/components/hpDetailBoxes/HpInfoBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpMessageBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpSrIIIBox.jsx
- er-allimi/src/components/hpDetailBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/ClosedBox.jsx
- er-allimi/src/components/ui/index.js
- er-allimi/src/pages/HpDetailBoxes.jsx
- er-allimi/src/pages/HpDetailPage.jsx
- 병원 디테일 페이지 기본 레이아웃 구현
- 기본 정보 박스를 제외한 실시간 응급실 가용 병상 박스, 실시간 입원실 가용 병상 박스, 중증 질환 정보 박스는 여닫기가 가능한 박스 ui로 구현
- HpDetailPage 레이아웃 구현
- HpDetailBoxes 레이아웃 구현
> [Feat] hpDetailPage layout 구현

- er-allimi/src/constants/index.js
- er-allimi/src/constants/kmToMUnit.js
- er-allimi/src/pages/Map.jsx
- ersList의 페이지네이션으로 나눈 목록과 맵 마커의 목록 동기화(10개 단위)
- 중심 위치 변경 시 페이지네이션 recoil 초기화 시킴
> [Feat] ersList 페이지네이션 목록과 맵 마커 동기화

- er-allimi/src/components/hpDetailBoxes/HpMessageList.jsx
- er-allimi/src/hooks/index.js
- er-allimi/src/hooks/useFetchHpMsg.js
- er-allimi/src/services/getErMsg.js
- HpMessageBox에서 현재 주소 위치의 파라미터(병원id)를 가져와 응급실 및 중증질환 메시지 데이터 커스텀 훅을 호출함.
- useQuery 사용 시 onError API는 다음 버전에서 없어질 예정.
- 에러 처리를 전역에서 관리할 필요가 있음.
- 참고 자료 https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose
> [Feat] 응급실 및 중증질환 메시지 조회 useQuery 구현

- er-allimi/package.json
- er-allimi/src/App.jsx
- er-allimi/src/components/ersBoxes/ErrorMessage.jsx
- er-allimi/src/components/ersBoxes/RefreshButton.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/hooks/useFetchErList.jsx
- er-allimi/src/hooks/useFetchErsRTavailableBed.jsx
- er-allimi/src/hooks/useGetUserLocation.jsx
- er-allimi/src/main.jsx
- er-allimi/yarn.lock
- 사용자 위치 가져오는데 실패할 경우
- 응급실 목록 데이터를 가져오는데 실패할 경우
- 응급실 실시간 가용 병상 데이터를 가져오는데 실패할 경우
- 'react-hot-toast' 패키지 설치
- App에 Toaster 컴포넌트 추가
- RefreshButton 컴포넌트 생성
- ErrorMessage 컴포넌트 생성
- queryClient에 queryCache 옵션 추가해 global error 처리
- useGetUserLocation hook에서 에러 발생 시 alert 창 대신 toast 띄우게 수정
- useFetchErList hook에서 에러 발생 시 alert 창 대신 toast 띄우게 수정
- useFetchErsRTavailableBed hook에서 에러 발생 시 alert 창 대신 toast 띄우게 수정
> [Chore] 'react-hot-toast' 패키지 설치 & [Feat] RefreshButton, ErrorMessage 컴포넌트 구현 [Feat] 데이터 fetching 과정에서 에러 발생 시 토스트 띄움

- er-allimi/src/components/map/InfoWindowOverlay.jsx
- er-allimi/src/pages/Map.jsx
- [기존] 가용 병상이 0일 경우 인포윈도우 내용에 0만 나옴
- [원인] 
`가용병상 && 전체병상 && 보여줄 컴포넌트`
-[해결]
` 전체병상 && 보여줄 컴포넌트`
map에서 가용병상이 없으면 null값으로 보여줄 컴포넌트 prop으로 들어감.
따라서 컴포넌트에선 전체병상이 true인지 확인하면 됨.
> [Fix] 가용 병상이 0일 경우도 인포윈도우 생성

- er-allimi/src/components/ersBoxes/ErItem.jsx
- er-allimi/src/components/ersBoxes/SuccessMessage.jsx
- er-allimi/src/components/ersBoxes/index.js
- er-allimi/src/components/hpDetailBoxes/HpInfoBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpInfoContent.jsx
- er-allimi/src/components/hpDetailBoxes/index.js
- er-allimi/src/components/icons/index.js
- er-allimi/src/components/index.js
- er-allimi/src/utils/copyText.jsx
- er-allimi/src/utils/index.js
- 응급실 전화번호/주소 복사 성공 시 나타나는 토스트
- HpInfoBox
- toast에 넣을 SuccessMessage 컴포넌트 구현
- 특정 텍스트를 복사하는 copyText 함수 생성
- 성공 메시지를 인자로 받아, 복사 성공 시 토스트에 성공 메시지를 띄움
- 실패 메시지를 인자로 받아, 복사 실패 시 토스트에 실패 메시지를 띄움
- 병원 기본 정보를 담는 HpInfoContent 컴포넌트를 구현해, HpInfoBox에 담음
> [Feat] SuccessMessage 구현 & [Feat] copyText 함수 생성 & [Feat] HpInfoContent 구현

- er-allimi/src/hooks/useMarker.jsx
- 지동 중심 위치 이동 시, 반경 내 기존 마커들뿐만 아니라 인포윈도우 모두 같이 삭제되게 수정
> [Fix] 반경 내 마커를 삭제할 때, 인포윈도우도 같이 삭제

- er-allimi/src/components/hpDetailBoxes/HpMessageItem.jsx
- HpMessage에서 getDateStrByHvidate 함수를 사용해 msgDate 실 데이터와 연결
> [Feat] HpMessage에서 msgDate 실 데이터와 연결

- er-allimi/src/components/hpDetailBoxes/HpMessageBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpMessageItem.jsx
- er-allimi/src/components/hpDetailBoxes/HpMessageList.jsx
- er-allimi/src/components/hpDetailBoxes/HpMovingBox.jsx
- er-allimi/src/components/ui/AutoPlaySlider.jsx
- er-allimi/src/components/ui/Slider.jsx
- er-allimi/src/pages/HpDetailBoxes.jsx
- md < 화면 너비가 < lg일 때
- 화면 너비가 md 이하일 때
- Slider에 className prop 추가, dotsPosition에 따라 slideList의 align-items 변경
- AutoPlaySlider에 className prop 추가
- HpMessageItem/HpMessageList/HpMessageBox/HpDetailBoxes 반응형 처리
- HpMovingBox expand시, showHpMessageState atom 변경 지연
> [Feat] HpMessageBox 반응형 처리

- er-allimi/src/components/ersBoxes/CurrentLocationBox.jsx
- er-allimi/src/components/ersBoxes/CurrentLocationInput.jsx
- 메인 페이지 (화면 너비 > lg 일때)
- 메인 페이지 (화면 너비 < lg 일때)
- 상세 페이지 (화면 너비 > lg 일때)
- 상세 페이지 (화면 너비 < lg 일때)
- HpDetail 페이지에선 현위치 박스에서 위치찾기 버튼 안보이게 수정
> [Feat] HpDetail 페이지에선 위치찾기 버튼 안보이게 수정

- er-allimi/src/components/hpDetailBoxes/HpInfoContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtHrAvailableBedContent.jsx
- 병원 기본 정보 박스에서 응급실 가용 병상 정보 유무 문구 삭제
-  응급실 가용 정보 박스와 입원실 가용 정보 박스에서 정보 유무 가이드 문구 보여줌
-
> [Fix] 응급실 가용 병상 정보 없을 경우 가이드 메시지 출력

- er-allimi/src/components/ersBoxes/ErItem.jsx
- er-allimi/src/components/hpDetailBoxes/HpMessageBox.jsx
- er-allimi/src/components/hpDetailBoxes/HpSrIllContent.jsx
- er-allimi/src/constants/pathes.js
- er-allimi/src/pages/Map.jsx
- er-allimi/src/utils/pathes.js
- HpDetail 페이지의 url에 stage1, stage2 추가
- HpMessageBox/HpSrIllContent 컴포넌트에서 recoil의 hpTargetState가 아닌 url에서 직접 params 가져옴
- 지도 마커와 ErsList 박스에서 HpDetail 페이지로 가는 링크 url 수정
> [Refactor] HpDetail 페이지의 url에 stage1, stage2 추가

- er-allimi/src/components/hpDetailBoxes/HpMessageBox.jsx
- er-allimi/src/pages/HpDetailBoxes.jsx
- 뷰포트 md이하일 때, open 아이콘을 오른쪽으로 위치시킴
> [Refactor] 뷰포트 md이하일 때, open 아이콘 위치 이동

- er-allimi/src/components/ersBoxes/ErsContent.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- er-allimi/src/components/index.js
- er-allimi/src/components/ui/GuideBox.jsx
- er-allimi/src/components/ui/index.js
- 가이드 박스 UI 분리
- 실시간 응급실 가용 병상 정보 박스, erList 박스 적용
- lg일땐 tooltip, md 이하일땐 popover로 가이드 박스를 나타냄
> [Feat] 가이드 박스 UI 생성 & 실시간 응급실 가용 병상 정보 박스, erList 박스 적용

- er-allimi/src/components/ui/GuideBox.jsx
- 메인 페이지
- 병원 상세 페이지
-  메인페이지에서 GuideBox는 응급실일반 정보만 보이게 수정
> [Refactor] 메인페이지에서 GuideBox는 응급실일반 정보만 보이게 수정

- er-allimi/src/components/ersBoxes/ErsList.jsx
- er-allimi/src/pages/NotFoundPage.jsx
- ErList에서 페이지네이션 클릭 후 최상단으로 스크롤 이동
- NotFoundPage에 console.log 삭제
> [Fix] ErList에서 페이지네이션 클릭 후 최상단으로 스크롤 이동

- er-allimi/src/components/app/Navbar.jsx
- 수정 전
- 수정 후
- 브라우저 너비 md 이하일 때, 네브바가 현 위치 버튼에 가려지는 이슈를 해결하기 위해 `z-index: 101`로 설정
> [Fix] Navbar z-index 설정

- er-allimi/src/App.jsx
- er-allimi/src/components/ersBoxes/ErsList.jsx
- er-allimi/src/hooks/useFetchErList.jsx
- er-allimi/src/hooks/useFetchErsRTavailableBed.jsx
- React-query onSuccess 콜백 삭제 및 select 옵션으로 전역변수 업데이트
- ErsList에서 isFetching을 확인하기 위해 호출한 useQuery를 삭제하고 router의 context를 사용해서 porps로 isFetching을 내려줌
> [Refactor] React-query onSuccess 콜백 삭제 및 select 옵션으로 전역변수 업데이트

- er-allimi/src/components/ui/Button.tsx
- er-allimi/src/components/ui/Dropdown.tsx
- er-allimi/src/components/ui/Input.tsx
- er-allimi/src/styles/theme.ts
- '@emotion/react' 모듈 내에서 export하는 Theme 인터페이스를 extends 키워드를 사용해 기존 theme 타입 전부 추가
- Input, Dropdown, Button 파일에서 `styled.[html요소]`의 제너릭에 입력한 인터페이스에서 theme 속성 타입 제거
> [Refactor] Theme 인터페이스에 기존 theme 타입 추가, styled 제너릭에 입력한 인터페이스에서 theme 속성 제거

- er-allimi/global.d.ts
- er-allimi/src/hooks/useFetchErList.tsx
- er-allimi/src/hooks/useFetchErsRTavailableBed.tsx
- er-allimi/src/hooks/useFetchHpMsg.tsx
- er-allimi/src/hooks/useFetchHpSrIII.jsx
- er-allimi/src/stores/atoms/ersListState.ts
- er-allimi/src/stores/atoms/ersRTavailableBedState.ts
- `global.d.ts` 파일 생성
- atoms/ersListState 파일 내 인터페이스를  `global.d.ts`로 옮김
- atoms/ersRTavailableBedState 내 인터페이스를  `global.d.ts`로 옮김
- useFetchErList 파일 ts 변환
- useFetchErsRTavailableBed 파일 ts 변환
- useFetchHpMsg 파일 ts 변환, staleTime/cacheTime을 29 -> 30초로 변경
- useFetchHpSrIll staleTime/cacheTime을 29 -> 30초로 변경
> [Refactor] hooks 폴더 내 일부 파일들 ts로 변환, useQuery의 staleTime/cacheTime을 30초로 변경

- er-allimi/src/components/hpDetailBoxes/ErChart.jsx
- er-allimi/src/components/hpDetailBoxes/HpRtErAvailableBedContent.jsx
- chart legend 제거(`display: none` 처리)
- bb의 size height를 100 -> 90으로 변경
- chart 간 row-gap 설정
- legend를 chart 하위로 옮겨보려 노력했으나, 마땅한 방법을 찾지 못해 일단 화면 상에 나타나지 않게 했음. 차후 수정 필요.
> [Fix] 실시간 응급실 가용 병상 박스에서 각 chart의 legend 제거

- er-allimi/src/components/app/NoticeModal.tsx
- er-allimi/src/constants/index.ts
- er-allimi/src/constants/sessionStorage.ts
- VISITED 상수 변수 생성
- sessionStorage를 사용해 새 탭에 첫 방문 시에만 공지사항 모달창이 뜨도록 수정
> [Refactor] sessionStorage를 사용해 새 탭에 첫 방문 시에만 공지사항 모달창이 뜨도록 수정
